# This is a basic workflow to help you get started with Actions

name: Frontend

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow when a new backend version is up and running 
  workflow_run:
    workflows: 
      - Backend
    branches:
      - master
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: |
            frontend/.next/cache
            frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('frontend/yarn.lock') }}

      - name: Install Yarn
        uses: borales/actions-yarn@v2.0.0

      - name: Install Dependencies
        run: yarn install --ignore-engines

      - name: Add Secrets to .env.production
        run: |
          echo "STRAPI_PREVIEW_SECRET=${{ secrets.STRAPI_PREVIEW_SECRET }}" >> .env.production
          
      - name: Build Next Application
        run: yarn build
      
      - name: Upload .next folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: | 
            frontend/.next
            !frontend/.next/cache

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Download .next folder
        uses: actions/download-artifact@v2
        with:
          name: build
          path: frontend/.next
      
      - name: Deploy Next Application
        run: gcloud app deploy
